[0m21:21:38.675640 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10965dd10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096e49d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096e5110>]}


============================== 21:21:38.678425 | e1bfbc79-4f06-4d72-b82b-323503727554 ==============================
[0m21:21:38.678425 [info ] [MainThread]: Running with dbt=1.9.4
[0m21:21:38.678761 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/dylanlam/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:21:38.679123 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/dylanlam/Documents/GitHub/dylan_eric_sp25/project6/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:21:38.680690 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.04392596, "process_in_blocks": "0", "process_kernel_time": 0.139317, "process_mem_max_rss": "101416960", "process_out_blocks": "0", "process_user_time": 0.560024}
[0m21:21:38.681121 [debug] [MainThread]: Command `dbt docs generate` failed at 21:21:38.681052 after 0.04 seconds
[0m21:21:38.681390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096e4d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10965e250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105680c90>]}
[0m21:21:38.681628 [debug] [MainThread]: Flushing usage events
[0m21:21:38.897607 [debug] [MainThread]: An error was encountered while trying to flush usage events
